# TCL File Generated by Component Editor 20.1
# Fri Jul 03 09:44:04 JST 2020
# DO NOT MODIFY


# 
# avalon_st_clock_bridge "Avalon-ST Clock Bridge" v1.0
# Fujii Naomichi 2020.07.03.09:44:04
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_st_clock_bridge
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_st_clock_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Fujii Naomichi"
set_module_property DISPLAY_NAME "Avalon-ST Clock Bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property VALIDATION_CALLBACK validation_callback
set_module_property ELABORATION_CALLBACK elaboration_callback



# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_st_clock_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file avalon_st_clock_bridge.sv SYSTEM_VERILOG PATH avalon_st_clock_bridge.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avalon_st_clock_bridge
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file avalon_st_clock_bridge.sv SYSTEM_VERILOG PATH avalon_st_clock_bridge.sv


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 8 ""
set_parameter_property DATA_WIDTH UNITS "Bits"
set_parameter_property DATA_WIDTH ALLOWED_RANGES 1:256
set_parameter_property DATA_WIDTH HDL_PARAMETER true

add_parameter SYMBOL_WIDTH INTEGER 8 ""
set_parameter_property SYMBOL_WIDTH UNITS "Bits"
set_parameter_property SYMBOL_WIDTH ALLOWED_RANGES 1:256

add_parameter CHANNEL_WIDTH INTEGER 0 ""
set_parameter_property CHANNEL_WIDTH UNITS "Bits"
set_parameter_property CHANNEL_WIDTH ALLOWED_RANGES 1:8
set_parameter_property CHANNEL_WIDTH HDL_PARAMETER true

add_parameter CHANNEL_WIDTH_ACTUAL INTEGER 1
set_parameter_property CHANNEL_WIDTH_ACTUAL VISIBLE false
set_parameter_property CHANNEL_WIDTH_ACTUAL DERIVED true

add_parameter USE_READY BOOLEAN 1
set_parameter_property USE_READY DISPLAY_NAME "Use input's ready signal"

add_parameter USE_ERROR BOOLEAN 1
set_parameter_property USE_ERROR DISPLAY_NAME "Use error signal"

proc validation_callback {} {
    set channel_width [get_parameter_value CHANNEL_WIDTH]
    if {0 < $channel_width} {
        set_parameter_value CHANNEL_WIDTH_ACTUAL $channel_width
    } else {
        set_parameter_value CHANNEL_WIDTH_ACTUAL 1
    }
}

proc elaboration_callback {} {
    set symbol_width [get_parameter_value SYMBOL_WIDTH]
    set_interface_property sink dataBitsPerSymbol $symbol_width
    set_interface_property source dataBitsPerSymbol $symbol_width
    set channel_width [get_parameter_value CHANNEL_WIDTH]
    set max_channel [expr 2 ** [get_parameter_value CHANNEL_WIDTH] - 1]
    set_interface_property sink maxChannel $max_channel
    set_interface_property source maxChannel $max_channel
    if {0 < $channel_width} {
        set_port_property sink_channel TERMINATION false
        set_port_property source_channel TERMINATION false
    } else {
        set_port_property sink_channel TERMINATION true
        set_port_property source_channel TERMINATION true
    }
    set use_ready [get_parameter_value USE_READY]
    set use_error [get_parameter_value USE_ERROR]
    if {$use_ready} {
        set_port_property sink_ready TERMINATION false
    } else {
        set_port_property sink_ready TERMINATION true
    }
    if {$use_error} {
        set_port_property sink_error TERMINATION false
        set_port_property source_error TERMINATION false
    } else {
        set_port_property sink_error TERMINATION true
        set_port_property source_error TERMINATION true
    }
}


# 
# display items
# 


# 
# connection point clk1
# 
add_interface clk1 clock end
set_interface_property clk1 clockRate 0
set_interface_property clk1 ENABLED true
set_interface_property clk1 EXPORT_OF ""
set_interface_property clk1 PORT_NAME_MAP ""
set_interface_property clk1 CMSIS_SVD_VARIABLES ""
set_interface_property clk1 SVD_ADDRESS_GROUP ""

add_interface_port clk1 clk1 clk Input 1


# 
# connection point reset1
# 
add_interface reset1 reset end
set_interface_property reset1 associatedClock clk1
set_interface_property reset1 synchronousEdges DEASSERT
set_interface_property reset1 ENABLED true

add_interface_port reset1 reset1 reset Input 1


# 
# connection point sink
# 
add_interface sink avalon_streaming end
set_interface_property sink associatedClock clk1
set_interface_property sink associatedReset reset1
set_interface_property sink dataBitsPerSymbol 8
set_interface_property sink errorDescriptor ""
set_interface_property sink firstSymbolInHighOrderBits true
set_interface_property sink maxChannel 0
set_interface_property sink readyLatency 0
set_interface_property sink ENABLED true

add_interface_port sink sink_data data Input DATA_WIDTH
add_interface_port sink sink_channel channel Input CHANNEL_WIDTH_ACTUAL
add_interface_port sink sink_valid valid Input 1
add_interface_port sink sink_ready ready Output 1
add_interface_port sink sink_error error Input 1


# 
# connection point clk2
# 
add_interface clk2 clock end
set_interface_property clk2 clockRate 0
set_interface_property clk2 ENABLED true

add_interface_port clk2 clk2 clk Input 1


# 
# connection point reset2
# 
add_interface reset2 reset end
set_interface_property reset2 associatedClock clk2
set_interface_property reset2 synchronousEdges DEASSERT
set_interface_property reset2 ENABLED true

add_interface_port reset2 reset2 reset Input 1


# 
# connection point source
# 
add_interface source avalon_streaming start
set_interface_property source associatedClock clk2
set_interface_property source associatedReset reset2
set_interface_property source dataBitsPerSymbol 8
set_interface_property source errorDescriptor ""
set_interface_property source firstSymbolInHighOrderBits true
set_interface_property source maxChannel 0
set_interface_property source readyLatency 0
set_interface_property source ENABLED true

add_interface_port source source_data data Output DATA_WIDTH
add_interface_port source source_channel channel Output CHANNEL_WIDTH_ACTUAL
add_interface_port source source_valid valid Output 1
add_interface_port source source_error error Output 1
add_interface_port source source_ready ready Input 1

