	controller u0 (
		.adc2_i2c_sda_in           (<connected-to-adc2_i2c_sda_in>),           //   adc2_i2c.sda_in
		.adc2_i2c_scl_in           (<connected-to-adc2_i2c_scl_in>),           //           .scl_in
		.adc2_i2c_sda_oe           (<connected-to-adc2_i2c_sda_oe>),           //           .sda_oe
		.adc2_i2c_scl_oe           (<connected-to-adc2_i2c_scl_oe>),           //           .scl_oe
		.clk_clk                   (<connected-to-clk_clk>),                   //        clk.clk
		.pio_1_export              (<connected-to-pio_1_export>),              //      pio_1.export
		.pio_2_export              (<connected-to-pio_2_export>),              //      pio_2.export
		.imu_spi_mosi              (<connected-to-imu_spi_mosi>),              //    imu_spi.mosi
		.imu_spi_miso              (<connected-to-imu_spi_miso>),              //           .miso
		.imu_spi_sclk              (<connected-to-imu_spi_sclk>),              //           .sclk
		.imu_spi_cs_n              (<connected-to-imu_spi_cs_n>),              //           .cs_n
		.imu_spi_int_n             (<connected-to-imu_spi_int_n>),             //           .int_n
		.pio_0_export              (<connected-to-pio_0_export>),              //      pio_0.export
		.reset_reset_n             (<connected-to-reset_reset_n>),             //      reset.reset_n
		.vc_encoder_encoder_1_data (<connected-to-vc_encoder_encoder_1_data>), // vc_encoder.encoder_1_data
		.vc_encoder_encoder_2_data (<connected-to-vc_encoder_encoder_2_data>), //           .encoder_2_data
		.vc_encoder_encoder_3_data (<connected-to-vc_encoder_encoder_3_data>), //           .encoder_3_data
		.vc_encoder_encoder_4_data (<connected-to-vc_encoder_encoder_4_data>), //           .encoder_4_data
		.vc_fault_fault            (<connected-to-vc_fault_fault>),            //   vc_fault.fault
		.vc_imeas1_data            (<connected-to-vc_imeas1_data>),            //  vc_imeas1.data
		.vc_imeas1_valid           (<connected-to-vc_imeas1_valid>),           //           .valid
		.vc_imeas2_data            (<connected-to-vc_imeas2_data>),            //  vc_imeas2.data
		.vc_imeas2_valid           (<connected-to-vc_imeas2_valid>),           //           .valid
		.vc_imeas3_data            (<connected-to-vc_imeas3_data>),            //  vc_imeas3.data
		.vc_imeas3_valid           (<connected-to-vc_imeas3_valid>),           //           .valid
		.vc_imeas4_data            (<connected-to-vc_imeas4_data>),            //  vc_imeas4.data
		.vc_imeas4_valid           (<connected-to-vc_imeas4_valid>),           //           .valid
		.vc_iref1_data             (<connected-to-vc_iref1_data>),             //   vc_iref1.data
		.vc_iref1_valid            (<connected-to-vc_iref1_valid>),            //           .valid
		.vc_iref2_data             (<connected-to-vc_iref2_data>),             //   vc_iref2.data
		.vc_iref2_valid            (<connected-to-vc_iref2_valid>),            //           .valid
		.vc_iref3_data             (<connected-to-vc_iref3_data>),             //   vc_iref3.data
		.vc_iref3_valid            (<connected-to-vc_iref3_valid>),            //           .valid
		.vc_iref4_data             (<connected-to-vc_iref4_data>),             //   vc_iref4.data
		.vc_iref4_valid            (<connected-to-vc_iref4_valid>),            //           .valid
		.vc_param_kp               (<connected-to-vc_param_kp>),               //   vc_param.kp
		.vc_param_ki               (<connected-to-vc_param_ki>),               //           .ki
		.vc_status_driver_otw_n    (<connected-to-vc_status_driver_otw_n>),    //  vc_status.driver_otw_n
		.vc_status_driver_fault_n  (<connected-to-vc_status_driver_fault_n>),  //           .driver_fault_n
		.vc_status_hall_fault_n    (<connected-to-vc_status_hall_fault_n>),    //           .hall_fault_n
		.vc_status_encoder_fault_n (<connected-to-vc_status_encoder_fault_n>), //           .encoder_fault_n
		.vc_status_pos_error       (<connected-to-vc_status_pos_error>),       //           .pos_error
		.vc_status_pos_uncertain   (<connected-to-vc_status_pos_uncertain>),   //           .pos_uncertain
		.mc_fault_fault            (<connected-to-mc_fault_fault>),            //   mc_fault.fault
		.mc_status_driver_otw_n    (<connected-to-mc_status_driver_otw_n>),    //  mc_status.driver_otw_n
		.mc_status_driver_fault_n  (<connected-to-mc_status_driver_fault_n>),  //           .driver_fault_n
		.mc_status_hall_fault_n    (<connected-to-mc_status_hall_fault_n>),    //           .hall_fault_n
		.mc_pwm_data               (<connected-to-mc_pwm_data>),               //     mc_pwm.data
		.mc_pwm_valid              (<connected-to-mc_pwm_valid>),              //           .valid
		.mc_pwm_ready              (<connected-to-mc_pwm_ready>)               //           .ready
	);

