# TCL File Generated by Component Editor 20.1
# Mon Jun 29 23:47:52 JST 2020
# DO NOT MODIFY


# 
# motor_controller "Motor Controller" v1.0
# Fujii Naomichi 2020.06.29.23:47:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module motor_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME motor_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Fujii Naomichi"
set_module_property DISPLAY_NAME "Motor Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL motor_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file motor_controller.sv SYSTEM_VERILOG PATH motor_controller.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL motor_controller
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file motor_controller.sv SYSTEM_VERILOG PATH motor_controller.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1


# 
# connection point fault
# 
add_interface fault conduit end
set_interface_property fault associatedClock clk
set_interface_property fault associatedReset reset
set_interface_property fault ENABLED true
set_interface_property fault EXPORT_OF ""
set_interface_property fault PORT_NAME_MAP ""
set_interface_property fault CMSIS_SVD_VARIABLES ""
set_interface_property fault SVD_ADDRESS_GROUP ""

add_interface_port fault fault fault Output 1


# 
# connection point status
# 
add_interface status conduit end
set_interface_property status associatedClock clk
set_interface_property status associatedReset reset
set_interface_property status ENABLED true
set_interface_property status EXPORT_OF ""
set_interface_property status PORT_NAME_MAP ""
set_interface_property status CMSIS_SVD_VARIABLES ""
set_interface_property status SVD_ADDRESS_GROUP ""

add_interface_port status status_driver_otw_n driver_otw_n Input 1
add_interface_port status status_driver_fault_n driver_fault_n Input 1
add_interface_port status status_hall_fault_n hall_fault_n Input 1


# 
# connection point pwm_source
# 
add_interface pwm_source avalon_streaming start
set_interface_property pwm_source associatedClock clk
set_interface_property pwm_source associatedReset reset
set_interface_property pwm_source dataBitsPerSymbol 8
set_interface_property pwm_source errorDescriptor ""
set_interface_property pwm_source firstSymbolInHighOrderBits true
set_interface_property pwm_source maxChannel 0
set_interface_property pwm_source readyLatency 0
set_interface_property pwm_source ENABLED true

add_interface_port pwm_source pwm_source_data data Output 16
add_interface_port pwm_source pwm_source_valid valid Output 1
add_interface_port pwm_source pwm_source_ready ready Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clk
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 1
set_interface_property slave readWaitStates 0
set_interface_property slave readWaitTime 0
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true

add_interface_port slave slave_address address Input 2
add_interface_port slave slave_readdata readdata Output 16
add_interface_port slave slave_writedata writedata Input 16
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_write write Input 1
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint slave
set_interface_property irq associatedClock clk
set_interface_property irq associatedReset reset
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq irq Output 1
