# TCL File Generated by Component Editor 20.1
# Sat Sep 26 23:43:22 JST 2020
# DO NOT MODIFY


# 
# vector_controller_master "Vector Controller Master" v1.0
# Fujii Naomichi 2020.09.26.23:43:22
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vector_controller_master
# 
set_module_property DESCRIPTION ""
set_module_property NAME vector_controller_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Fujii Naomichi"
set_module_property DISPLAY_NAME "Vector Controller Master"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vector_controller_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file vector_controller_master.sv VERILOG PATH vector_controller_master.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL vector_controller_master
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file vector_controller_master.sv VERILOG PATH vector_controller_master.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point fault
# 
add_interface fault conduit end
set_interface_property fault associatedClock clk
set_interface_property fault associatedReset reset
set_interface_property fault ENABLED true
set_interface_property fault EXPORT_OF ""
set_interface_property fault PORT_NAME_MAP ""
set_interface_property fault CMSIS_SVD_VARIABLES ""
set_interface_property fault SVD_ADDRESS_GROUP ""

add_interface_port fault fault fault Output 1


# 
# connection point status
# 
add_interface status conduit end
set_interface_property status associatedClock clk
set_interface_property status associatedReset reset
set_interface_property status ENABLED true
set_interface_property status EXPORT_OF ""
set_interface_property status PORT_NAME_MAP ""
set_interface_property status CMSIS_SVD_VARIABLES ""
set_interface_property status SVD_ADDRESS_GROUP ""

add_interface_port status status_driver_otw_n driver_otw_n Input 4
add_interface_port status status_driver_fault_n driver_fault_n Input 4
add_interface_port status status_hall_fault_n hall_fault_n Input 4
add_interface_port status status_encoder_fault_n encoder_fault_n Input 4
add_interface_port status status_pos_error pos_error Input 4
add_interface_port status status_pos_uncertain pos_uncertain Input 4


# 
# connection point encoder
# 
add_interface encoder conduit end
set_interface_property encoder associatedClock clk
set_interface_property encoder associatedReset reset
set_interface_property encoder ENABLED true
set_interface_property encoder EXPORT_OF ""
set_interface_property encoder PORT_NAME_MAP ""
set_interface_property encoder CMSIS_SVD_VARIABLES ""
set_interface_property encoder SVD_ADDRESS_GROUP ""

add_interface_port encoder encoder_1_data encoder_1_data Input 16
add_interface_port encoder encoder_2_data encoder_2_data Input 16
add_interface_port encoder encoder_3_data encoder_3_data Input 16
add_interface_port encoder encoder_4_data encoder_4_data Input 16


# 
# connection point param
# 
add_interface param conduit end
set_interface_property param associatedClock clk
set_interface_property param associatedReset reset
set_interface_property param ENABLED true
set_interface_property param EXPORT_OF ""
set_interface_property param PORT_NAME_MAP ""
set_interface_property param CMSIS_SVD_VARIABLES ""
set_interface_property param SVD_ADDRESS_GROUP ""

add_interface_port param param_kp kp Output 16
add_interface_port param param_ki ki Output 16


# 
# connection point current_measurement_1
# 
add_interface current_measurement_1 avalon_streaming end
set_interface_property current_measurement_1 associatedClock clk
set_interface_property current_measurement_1 associatedReset reset
set_interface_property current_measurement_1 dataBitsPerSymbol 16
set_interface_property current_measurement_1 errorDescriptor ""
set_interface_property current_measurement_1 firstSymbolInHighOrderBits true
set_interface_property current_measurement_1 maxChannel 0
set_interface_property current_measurement_1 readyLatency 0
set_interface_property current_measurement_1 ENABLED true
set_interface_property current_measurement_1 EXPORT_OF ""
set_interface_property current_measurement_1 PORT_NAME_MAP ""
set_interface_property current_measurement_1 CMSIS_SVD_VARIABLES ""
set_interface_property current_measurement_1 SVD_ADDRESS_GROUP ""

add_interface_port current_measurement_1 current_measurement_1_data data Input 32
add_interface_port current_measurement_1 current_measurement_1_valid valid Input 1


# 
# connection point current_measurement_2
# 
add_interface current_measurement_2 avalon_streaming end
set_interface_property current_measurement_2 associatedClock clk
set_interface_property current_measurement_2 associatedReset reset
set_interface_property current_measurement_2 dataBitsPerSymbol 16
set_interface_property current_measurement_2 errorDescriptor ""
set_interface_property current_measurement_2 firstSymbolInHighOrderBits true
set_interface_property current_measurement_2 maxChannel 0
set_interface_property current_measurement_2 readyLatency 0
set_interface_property current_measurement_2 ENABLED true
set_interface_property current_measurement_2 EXPORT_OF ""
set_interface_property current_measurement_2 PORT_NAME_MAP ""
set_interface_property current_measurement_2 CMSIS_SVD_VARIABLES ""
set_interface_property current_measurement_2 SVD_ADDRESS_GROUP ""

add_interface_port current_measurement_2 current_measurement_2_data data Input 32
add_interface_port current_measurement_2 current_measurement_2_valid valid Input 1


# 
# connection point current_measurement_3
# 
add_interface current_measurement_3 avalon_streaming end
set_interface_property current_measurement_3 associatedClock clk
set_interface_property current_measurement_3 associatedReset reset
set_interface_property current_measurement_3 dataBitsPerSymbol 16
set_interface_property current_measurement_3 errorDescriptor ""
set_interface_property current_measurement_3 firstSymbolInHighOrderBits true
set_interface_property current_measurement_3 maxChannel 0
set_interface_property current_measurement_3 readyLatency 0
set_interface_property current_measurement_3 ENABLED true
set_interface_property current_measurement_3 EXPORT_OF ""
set_interface_property current_measurement_3 PORT_NAME_MAP ""
set_interface_property current_measurement_3 CMSIS_SVD_VARIABLES ""
set_interface_property current_measurement_3 SVD_ADDRESS_GROUP ""

add_interface_port current_measurement_3 current_measurement_3_data data Input 32
add_interface_port current_measurement_3 current_measurement_3_valid valid Input 1


# 
# connection point current_measurement_4
# 
add_interface current_measurement_4 avalon_streaming end
set_interface_property current_measurement_4 associatedClock clk
set_interface_property current_measurement_4 associatedReset reset
set_interface_property current_measurement_4 dataBitsPerSymbol 16
set_interface_property current_measurement_4 errorDescriptor ""
set_interface_property current_measurement_4 firstSymbolInHighOrderBits true
set_interface_property current_measurement_4 maxChannel 0
set_interface_property current_measurement_4 readyLatency 0
set_interface_property current_measurement_4 ENABLED true
set_interface_property current_measurement_4 EXPORT_OF ""
set_interface_property current_measurement_4 PORT_NAME_MAP ""
set_interface_property current_measurement_4 CMSIS_SVD_VARIABLES ""
set_interface_property current_measurement_4 SVD_ADDRESS_GROUP ""

add_interface_port current_measurement_4 current_measurement_4_data data Input 32
add_interface_port current_measurement_4 current_measurement_4_valid valid Input 1


# 
# connection point current_reference_1
# 
add_interface current_reference_1 avalon_streaming start
set_interface_property current_reference_1 associatedClock clk
set_interface_property current_reference_1 associatedReset reset
set_interface_property current_reference_1 dataBitsPerSymbol 16
set_interface_property current_reference_1 errorDescriptor ""
set_interface_property current_reference_1 firstSymbolInHighOrderBits true
set_interface_property current_reference_1 maxChannel 0
set_interface_property current_reference_1 readyLatency 0
set_interface_property current_reference_1 ENABLED true
set_interface_property current_reference_1 EXPORT_OF ""
set_interface_property current_reference_1 PORT_NAME_MAP ""
set_interface_property current_reference_1 CMSIS_SVD_VARIABLES ""
set_interface_property current_reference_1 SVD_ADDRESS_GROUP ""

add_interface_port current_reference_1 current_reference_1_data data Output 32
add_interface_port current_reference_1 current_reference_1_valid valid Output 1


# 
# connection point current_reference_2
# 
add_interface current_reference_2 avalon_streaming start
set_interface_property current_reference_2 associatedClock clk
set_interface_property current_reference_2 associatedReset reset
set_interface_property current_reference_2 dataBitsPerSymbol 16
set_interface_property current_reference_2 errorDescriptor ""
set_interface_property current_reference_2 firstSymbolInHighOrderBits true
set_interface_property current_reference_2 maxChannel 0
set_interface_property current_reference_2 readyLatency 0
set_interface_property current_reference_2 ENABLED true
set_interface_property current_reference_2 EXPORT_OF ""
set_interface_property current_reference_2 PORT_NAME_MAP ""
set_interface_property current_reference_2 CMSIS_SVD_VARIABLES ""
set_interface_property current_reference_2 SVD_ADDRESS_GROUP ""

add_interface_port current_reference_2 current_reference_2_data data Output 32
add_interface_port current_reference_2 current_reference_2_valid valid Output 1


# 
# connection point current_reference_3
# 
add_interface current_reference_3 avalon_streaming start
set_interface_property current_reference_3 associatedClock clk
set_interface_property current_reference_3 associatedReset reset
set_interface_property current_reference_3 dataBitsPerSymbol 16
set_interface_property current_reference_3 errorDescriptor ""
set_interface_property current_reference_3 firstSymbolInHighOrderBits true
set_interface_property current_reference_3 maxChannel 0
set_interface_property current_reference_3 readyLatency 0
set_interface_property current_reference_3 ENABLED true
set_interface_property current_reference_3 EXPORT_OF ""
set_interface_property current_reference_3 PORT_NAME_MAP ""
set_interface_property current_reference_3 CMSIS_SVD_VARIABLES ""
set_interface_property current_reference_3 SVD_ADDRESS_GROUP ""

add_interface_port current_reference_3 current_reference_3_data data Output 32
add_interface_port current_reference_3 current_reference_3_valid valid Output 1


# 
# connection point current_reference_4
# 
add_interface current_reference_4 avalon_streaming start
set_interface_property current_reference_4 associatedClock clk
set_interface_property current_reference_4 associatedReset reset
set_interface_property current_reference_4 dataBitsPerSymbol 16
set_interface_property current_reference_4 errorDescriptor ""
set_interface_property current_reference_4 firstSymbolInHighOrderBits true
set_interface_property current_reference_4 maxChannel 0
set_interface_property current_reference_4 readyLatency 0
set_interface_property current_reference_4 ENABLED true
set_interface_property current_reference_4 EXPORT_OF ""
set_interface_property current_reference_4 PORT_NAME_MAP ""
set_interface_property current_reference_4 CMSIS_SVD_VARIABLES ""
set_interface_property current_reference_4 SVD_ADDRESS_GROUP ""

add_interface_port current_reference_4 current_reference_4_data data Output 32
add_interface_port current_reference_4 current_reference_4_valid valid Output 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clk
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_address address Input 5
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_readdata readdata Output 16
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_writedata writedata Input 16
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint slave
set_interface_property irq associatedClock clk
set_interface_property irq associatedReset reset
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq irq Output 1
