# TCL File Generated by Component Editor 20.1
# Sat Aug 22 21:53:26 JST 2020
# DO NOT MODIFY


# 
# imu_spim "IMU SPI Master" v1.0
# Fujii Naomichi 2020.08.22.21:53:26
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 12.0


# 
# module imu_spim
# 
set_module_property DESCRIPTION ""
set_module_property NAME imu_spim
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Fujii Naomichi"
set_module_property DISPLAY_NAME "IMU SPI Master"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL imu_spim
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file imu_spim.sv SYSTEM_VERILOG PATH imu_spim.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL imu_spim
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file imu_spim.sv SYSTEM_VERILOG PATH imu_spim.sv


# 
# parameters
# 
add_parameter PRESCALER INTEGER 1
set_parameter_property PRESCALER DISPLAY_NAME "Prescaler"
set_parameter_property PRESCALER ALLOWED_RANGES 1:2147483647
set_parameter_property PRESCALER HDL_PARAMETER true
set_parameter_property PRESCALER AFFECTS_GENERATION true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clk
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_address address Input 3
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_readdata readdata Output 16
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_writedata writedata Input 16
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point spis
# 
add_interface spis conduit end
set_interface_property spis ENABLED true
set_interface_property spis EXPORT_OF ""
set_interface_property spis PORT_NAME_MAP ""
set_interface_property spis CMSIS_SVD_VARIABLES ""
set_interface_property spis SVD_ADDRESS_GROUP ""

add_interface_port spis SCLK export Input 1
add_interface_port spis MOSI export Input 1
add_interface_port spis MISO export Output 1
add_interface_port spis SS_n export Input 1


# 
# connection point spim
# 
add_interface spim conduit end
set_interface_property spim associatedClock clk
set_interface_property spim associatedReset reset
set_interface_property spim ENABLED true
set_interface_property spim EXPORT_OF ""
set_interface_property spim PORT_NAME_MAP ""
set_interface_property spim CMSIS_SVD_VARIABLES ""
set_interface_property spim SVD_ADDRESS_GROUP ""

add_interface_port spim spim_mosi mosi Output 1
add_interface_port spim spim_miso miso Input 1
add_interface_port spim spim_sclk sclk Output 1
add_interface_port spim spim_cs_n cs_n Output 1
add_interface_port spim spim_int_n int_n Input 1
