# TCL File Generated by Component Editor 18.1
# Sat Oct 10 22:41:32 JST 2020
# DO NOT MODIFY


# 
# i2c_master "I2C Master" v1.0
# Fujii Naomichi 2020.10.10.22:41:32
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module i2c_master
# 
set_module_property DESCRIPTION ""
set_module_property NAME i2c_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Fujii Naomichi"
set_module_property DISPLAY_NAME "I2C Master"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2c_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file i2c_master.sv SYSTEM_VERILOG PATH i2c_master.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL i2c_master
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file i2c_master.sv SYSTEM_VERILOG PATH i2c_master.sv


# 
# parameters
# 
add_parameter PRESCALER INTEGER 2 ""
set_parameter_property PRESCALER DEFAULT_VALUE 2
set_parameter_property PRESCALER DISPLAY_NAME PRESCALER
set_parameter_property PRESCALER TYPE INTEGER
set_parameter_property PRESCALER UNITS None
set_parameter_property PRESCALER ALLOWED_RANGES 2:2147483647
set_parameter_property PRESCALER DESCRIPTION ""
set_parameter_property PRESCALER AFFECTS_GENERATION false
set_parameter_property PRESCALER HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clk
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true

add_interface_port slave slave_address address Input 3
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_readdata readdata Output 16
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_writedata writedata Input 16
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint slave
set_interface_property irq associatedClock clk
set_interface_property irq associatedReset reset
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true

add_interface_port irq irq irq Output 1


# 
# connection point i2c
# 
add_interface i2c conduit end
set_interface_property i2c associatedClock clk
set_interface_property i2c associatedReset reset
set_interface_property i2c ENABLED true

add_interface_port i2c i2c_scl_in scl_in Input 1
add_interface_port i2c i2c_sda_in sda_in Input 1
add_interface_port i2c i2c_scl_oe scl_oe Output 1
add_interface_port i2c i2c_sda_oe sda_oe Output 1

