# TCL File Generated by Component Editor 18.1
# Sat Sep 21 15:40:41 JST 2019
# DO NOT MODIFY


# 
# avalon_st_uart_tx "Avalon-ST UART Transmitter" v1.0
#  2019.09.21.15:40:41
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_st_uart_tx
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_st_uart_tx
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon-ST UART Transmitter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property VALIDATION_CALLBACK verify_parameters


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_st_uart_tx
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file avalon_st_uart_tx.sv VERILOG PATH avalon_st_uart_tx.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avalon_st_uart_tx
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file avalon_st_uart_tx.sv VERILOG PATH avalon_st_uart_tx.sv


# 
# parameters
# 

add_parameter BAUD_RATE INTEGER 9600
set_parameter_property BAUD_RATE DISPLAY_NAME "Baud rate"
set_parameter_property BAUD_RATE ALLOWED_RANGES 1:2147483647
set_parameter_property BAUD_RATE AFFECTS_ELABORATION false

add_parameter CLOCK_RATE INTEGER 0
set_parameter_property CLOCK_RATE DISPLAY_NAME "Clock frequency"
set_parameter_property CLOCK_RATE SYSTEM_INFO {CLOCK_RATE clk}
set_parameter_property CLOCK_RATE DERIVED true
set_parameter_property CLOCK_RATE AFFECTS_ELABORATION false
set_parameter_property CLOCK_RATE VISIBLE true

add_parameter PRESCALER INTEGER 0
set_parameter_property PRESCALER DISPLAY_NAME "Prescaler"
set_parameter_property PRESCALER DERIVED true
set_parameter_property PRESCALER HDL_PARAMETER true
set_parameter_property PRESCALER AFFECTS_ELABORATION false

add_parameter BAUD_RATE_ERROR FLOAT 0.0
set_parameter_property BAUD_RATE_ERROR DISPLAY_NAME "Baud rate error (%)"
set_parameter_property BAUD_RATE_ERROR DERIVED true
set_parameter_property BAUD_RATE_ERROR AFFECTS_ELABORATION false

proc verify_parameters {} {
    set baud_rate [get_parameter_value BAUD_RATE]
    set clock_rate [get_parameter_value CLOCK_RATE]
    set prescaler [expr $clock_rate / $baud_rate]
    if {$clock_rate <= 0} {
        send_message error "Clock frequency is undetermined or zero."
    }
    if {$prescaler < 2} {
        send_message error "Prescaler value is zero."
    }
    set_parameter_value PRESCALER $prescaler
    if {(0 < $clock_rate) && (2 <= $prescaler)} {
        set actual_baud_rate [expr $clock_rate / $prescaler]
        set error [expr 100.0 * ($actual_baud_rate - $baud_rate) / $baud_rate]
        set_parameter_value BAUD_RATE_ERROR $error
    } else {
        set_parameter_value BAUD_RATE_ERROR 100.0
    }
}


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1


# 
# connection point sink
# 
add_interface sink avalon_streaming end
set_interface_property sink associatedClock clk
set_interface_property sink associatedReset reset
set_interface_property sink dataBitsPerSymbol 8
set_interface_property sink errorDescriptor ""
set_interface_property sink firstSymbolInHighOrderBits true
set_interface_property sink maxChannel 0
set_interface_property sink readyLatency 0
set_interface_property sink ENABLED true

add_interface_port sink sink_ready ready Output 1
add_interface_port sink sink_valid valid Input 1
add_interface_port sink sink_data data Input 8


# 
# connection point uart
# 
add_interface uart conduit end
set_interface_property uart associatedClock clk
set_interface_property uart associatedReset reset
set_interface_property uart ENABLED true

add_interface_port uart uart_txd txd Output 1
