# TCL File Generated by Component Editor 18.1
# Sat Sep 21 15:40:41 JST 2019
# DO NOT MODIFY


# 
# avalon_st_byte_converter "Avalon-ST Byte Converter" v1.0
#  2019.09.21.15:40:41
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_st_byte_converter
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_st_byte_converter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon-ST Byte Converter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK change_interfaces


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_st_byte_converter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file avalon_st_byte_converter.sv VERILOG PATH avalon_st_byte_converter.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avalon_st_byte_converter
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file avalon_st_byte_converter.sv VERILOG PATH avalon_st_byte_converter.sv


# 
# parameters
# 

add_parameter CHANNEL_WIDTH INTEGER 8
set_parameter_property CHANNEL_WIDTH DISPLAY_NAME "Channel Width"
set_parameter_property CHANNEL_WIDTH ALLOWED_RANGES 1:8
set_parameter_property CHANNEL_WIDTH HDL_PARAMETER true
set_parameter_property CHANNEL_WIDTH AFFECTS_ELABORATION true

add_parameter SYMBOL_WIDTH INTEGER 8
set_parameter_property SYMBOL_WIDTH DISPLAY_NAME "Symbol Width"
set_parameter_property SYMBOL_WIDTH ALLOWED_RANGES 1:32
set_parameter_property SYMBOL_WIDTH HDL_PARAMETER true
set_parameter_property SYMBOL_WIDTH AFFECTS_ELABORATION true


add_parameter SINK_SYMBOLS INTEGER 1
set_parameter_property SINK_SYMBOLS DISPLAY_NAME "Sink Symbols"
set_parameter_property SINK_SYMBOLS ALLOWED_RANGES 1:4
set_parameter_property SINK_SYMBOLS HDL_PARAMETER true
set_parameter_property SINK_SYMBOLS AFFECTS_ELABORATION true


proc change_interfaces {} {
    set channel_width [get_parameter_value CHANNEL_WIDTH]
    set max_channel [expr {pow(2, $channel_width) - 1}]
    set_interface_property sink maxChannel $max_channel
}


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1


# 
# connection point sink
# 
add_interface sink avalon_streaming end
set_interface_property sink associatedClock clk
set_interface_property sink associatedReset reset
set_interface_property sink dataBitsPerSymbol 8
set_interface_property sink errorDescriptor ""
set_interface_property sink firstSymbolInHighOrderBits true
set_interface_property sink maxChannel 0
set_interface_property sink readyLatency 0
set_interface_property sink ENABLED true

add_interface_port sink sink_ready ready Output 1
add_interface_port sink sink_valid valid Input 1
add_interface_port sink sink_data data Input {SYMBOL_WIDTH * SINK_SYMBOLS}
add_interface_port sink sink_channel channel Input CHANNEL_WIDTH


# 
# connection point source
# 
add_interface source avalon_streaming start
set_interface_property source associatedClock clk
set_interface_property source associatedReset reset
set_interface_property source dataBitsPerSymbol 8
set_interface_property source errorDescriptor ""
set_interface_property source firstSymbolInHighOrderBits true
set_interface_property source maxChannel 0
set_interface_property source readyLatency 0
set_interface_property source ENABLED true

add_interface_port source source_ready ready Input 1
add_interface_port source source_valid valid Output 1
add_interface_port source source_data data Output 8
